version: '3'
services:
  myservice:
    container_name: bottom-bot
    environment: 
      - BOT_TOKEN 
      - DB_NAME 
      - DB_COllECTION_NAME 
      - DB_USERNAME 
      - DB_PASSWORD 
    build:
      context: ./
      dockerfile: Dockerfile
    image: bottom-bot/latest